[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m scrumagent.main_discord_bot"
healthcheckPath = "/"
healthcheckTimeout = 100

[variables]
PYTHON_VERSION = "3.11"
