[build]
builder = "nixpacks"
buildCommand = "cp -f config/taiga_discord_maps.yaml.limbip config/taiga_discord_maps.yaml && pip install -r requirements.txt"

[deploy]
startCommand = "python -m scrumagent.main_discord_bot"

[variables]
PYTHON_VERSION = "3.11"
